name       : python-qtawesome
version    : 1.0.2
release    : 6
source     :
    - https://github.com/spyder-ide/qtawesome/archive/refs/tags/v1.0.2.tar.gz : 3cd0cd2a8d4c23a6f6246a0fe095786e33fd4ea7c4da23fc4b2694a1ec37f083
homepage   : https://github.com/spyder-ide/qtawesome
license    : MIT
component  : programming.python
summary    : Iconic fonts in PyQt and PySide applications
description: |
    QtAwesome enables iconic fonts such as Font Awesome and Elusive Icons in PyQt and PySide applications. It started as a Python port of the QtAwesome C++ library by Rick Blommers.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-qtpy
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
