name       : python-qtawesome
version    : 0.5.7
release    : 3
source     :
    - https://github.com/spyder-ide/qtawesome/archive/v0.5.7.tar.gz : 6a9be868b4f9993ca87ac405dac0d82187e16481ee6baf920ab4bee060efcb24
license    : MIT
component  : programming.python
summary    : Iconic fonts in PyQt and PySide applications.
description: |
    QtAwesome enables iconic fonts such as Font Awesome and Elusive Icons in PyQt and PySide applications. It started as a Python port of the QtAwesome C++ library by Rick Blommers.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-qtpy
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
