name       : python-qtawesome
version    : 1.2.2
release    : 12
source     :
    - https://github.com/spyder-ide/qtawesome/archive/refs/tags/v1.2.2.tar.gz : 09d6b837315c1618b34865a2a723b5bb415968b6c4b483cd39386ac85106d9fe
homepage   : https://github.com/spyder-ide/qtawesome
license    : MIT
component  : programming.python
summary    : Iconic fonts in PyQt and PySide applications
description: |
    QtAwesome enables iconic fonts such as Font Awesome and Elusive Icons in PyQt and PySide applications. It started as a Python port of the QtAwesome C++ library by Rick Blommers.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-qtpy
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
