name       : python-qtawesome
version    : 0.4.4
release    : 1
source     :
    - https://github.com/spyder-ide/qtawesome/archive/v0.4.4.tar.gz : f6cdc1546906c00019adf748d259ec68055113b65108e90ce7bd8a869eb3daf4
license    : MIT
component  : programming.python
summary    : Iconic fonts in PyQt and PySide applications.
description: |
    QtAwesome enables iconic fonts such as Font Awesome and Elusive Icons in PyQt and PySide applications. It started as a Python port of the QtAwesome C++ library by Rick Blommers.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - python-qtpy
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
