name       : python-qtawesome
version    : 1.1.1
release    : 9
source     :
    - https://github.com/spyder-ide/qtawesome/archive/refs/tags/v1.1.1.tar.gz : d15dc17188494ecbc34da0dec503874cb136d777752482da940ecd6d8fb2954e
homepage   : https://github.com/spyder-ide/qtawesome
license    : MIT
component  : programming.python
summary    : Iconic fonts in PyQt and PySide applications
description: |
    QtAwesome enables iconic fonts such as Font Awesome and Elusive Icons in PyQt and PySide applications. It started as a Python port of the QtAwesome C++ library by Rick Blommers.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python-qtpy
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
